### ISSUE TITLE
getRawString() should be getOriginalText()

### ISSUE THREAD

**Issue by AlextheYounga** [juzim/todo-txt-parser#1]
Honestly this issue is mainly to tell you how great this package is. Came in really handy on a Laravel project of mine and everything basically works as expected. I know it's been 8 years, but just wanted you to know it was useful to someone. Awesome work!

I had to add this line to the psr-4 property in composer.json in order for Laravel to recognize its namespace, but that's not a huge deal. 

```json
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "TodoTxtParser\\": "vendor/juzim/todo-txt-parser/lib/"
        }
    },
```

In the docs it says you can call `->getRawString()` but it looks like the actual property is `->getOriginalText()`. 

Again, not a huge deal at all. Thanks for this!

**Comment by juzim** [comment]
Great catch, I updated the readme. Thanks for your kind words, it's great that this project could be of use to you!

**Comment by juli-dot-md** [comment]
Great catch, I updated the readme. Thanks for your kind words, it's great that this project could be of use to you!
